export const PROFILE_UPDATING = 'PROFILE_UPDATING';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_ERROR = 'PROFILE_UPDATE_ERROR';

export const PROFILE_GETTING = 'PROFILE_GETTING';
export const PROFILE_GET_SUCCESS = 'PROFILE_GET_SUCCESS';
export const PROFILE_GET_ERROR = 'PROFILE_GET_ERROR';